### ISSUE TITLE
Error: Server disconnected without sending a response. Error: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by SusgUY446** [ollama/ollama-python#112]
when running this code 
![image](https://github.com/ollama/ollama-python/assets/129160115/35f80471-29bd-4d72-b6aa-f338c50a593f)
i get the error in the title. what did i do wrong or what is the issue here?

**Comment by nerdykamil** [comment]
Hi, how did you solve this? any guidance pls?

**Comment by SusgUY446** [comment]
> Hi, how did you solve this? any guidance pls?

i think i forgot to start the ollama server but i dont really know anymore
