### ISSUE TITLE
Feature request for less configuration by merging external library

### ISSUE THREAD

**Issue by leftmove** [ollama/ollama-python#128]
I created [cria](https://github.com/leftmove/cria), a Python library which takes this ollama and allows programmatic use with less configuration.

I created the library to address some of the pain points I had when using ollama for my personal project, but only now have I realized that perhaps the features I added would be better in the original ollama Python client.

Here are some of the features I added.
- Start ollama automatically when using the library
- Run multiple ollama models at once
- Automatically save chat history
- Open and close methods for running LLMs
- Allow use of `with` statements when loading models
There may be a couple I am missing.

I am saying all this to ask: would it be possible for me to add this features? I would be happy to code them all with the proper review and best practices implemented. I have already done most of the work (I think), and adding these features would not prove too much of a challenge.

Although I am happy to add to this library, I am unsure whether I even should. If `ollama-python` is best left as is, with more barebone features for external libraries to modify, perhaps my library should just stay external.

**Comment by mxyng** [comment]
Thanks for creating the issue. While I like many of the features you mentioned, this library is intended to be a thin Python wrapper around the Ollama API. As such those features would be out of scope.

However you're more than welcome to create a library building on top of this one or the Ollama API directly
