### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by p-vdp** [ollama/ollama-python#183]
I'm running ollama on a remote server and would like to interact with it from another machine via CLI and the REST API.

This should be pretty straightforward to do with a custom Client object in `__main__.py`. Usage from a terminal would be something like this:

`python -m ollama --endpoint http://remotehost:11434 --model llama3 --message "Why is the sky blue?"`

I'm interested in implementing this. Do folks have a preference for CLI parameter handling? I prefer [absl](https://abseil.io/docs/python/quickstart).

**Comment by synacktraa** [comment]
I prefer [Cyclopts](https://www.reddit.com/r/Python/comments/18hn2t1/cyclopts_a_cli_library_that_fixes_13_annoying/)

**Comment by mxyng** [comment]
As mentioned in #185, a CLI is be out of scope of this repo
