### ISSUE TITLE
Wrong host handling

### ISSUE THREAD

**Issue by racerxdl** [ollama/ollama-python#209]
According to this https://github.com/ollama/ollama-python/blob/main/ollama/_client.py#L906-L953 its using the host variable wrongly. It parses and strips everything from the path.

This does not allow the ollama to be hosted in a subpath, for example `/ollama0`.

**Comment by hansesm** [comment]
I can confirm this.

**Comment by ParthSareen** [comment]
Dont think we run into this anymore - closing out but feel free to open again!
