### ISSUE TITLE
ollama.generate和ollama.chat的区别是什么？

### ISSUE THREAD

**Issue by haomes** [ollama/ollama-python#21]

**Comment by MostlyKIGuess** [comment]
What's the issue btw?

**Comment by mxyng** [comment]
`ollama.generate` calls ollama's generate endpoint which is intended for text or code completion but can also be used for chat. it takes `prompt`, `template`, and `system` as its main input fields.

`ollama.chat` calls ollama's chat endpoint which is specialized for chat interactions. it takes `messages` as its main input field
