### ISSUE TITLE
Add way to abort a streaming response from chat / generate

### ISSUE THREAD

**Issue by paulrobello** [ollama/ollama-python#210]
I don't see any way to abort a streaming response from chat / generate methods

Is this or will this be supported?

Given the following snippet how can you properly abort the stream? Simply breaking from the for chunk loop is not enough.
```python
           stream = ollama.chat(
                model=model_name,
                messages=messages,
                stream=True,
           )
           msg_content = ""
           for chunk in stream:
               msg_content += chunk["message"]["content"]
```

**Comment by antoninoLorenzo** [comment]
Technically there is no way of doing it, as you can see in that [issue](https://github.com/ggerganov/llama.cpp/discussions/6212) on `llama.cpp` repository; the "brute-force" way is to add a `KeyboardInterrupt` during the stream, for example:

```python
try:
    for chunk in stream:
        print(chunk["message"]["content"], end='')
except KeyboardInterrupt:
    pass
```

However that approach may cause problems, the main one is that probably the Ollama server will continue sending stuff, however given that the stream is closed it will send chunks to nothing. To better understand what could happen you should have either `httpx` knowledge (what `_client.py` uses to make requests) or Go  knowledge (what `Ollama` is built in).

**Comment by mxyng** [comment]
exiting the generator is sufficient to abort the request and stop generation, e.g.

```python
           for chunk in stream:
               msg_content += chunk["message"]["content"]
               if should_break():
                   break
```

**Comment by wahba404** [comment]
Hi Mxyng, does this solution actually terminate the response generation as you would expect when using the API directly and hitting CTRL + C? 
If not, we break the stream, but the model is still using resources on the machine until its response is complete. I'm not sure about the python sdk, but the JS one does offer a proper abort method: https://github.com/ollama/ollama-js/blob/main/examples/abort/abort-single-request.ts

**Comment by whs** [comment]
I think I've found a workaround.

Simply throw an exception where you'd use `break`, then outside the `async for` you catch it:

```py
response = await ollama.AsyncClient().chat(...)
try:
    async for chunk in response:
        raise StopIteration
except StopIteration:
    pass
```

I can see that RST packets do get sent this way, and the server response with context canceled.
