### ISSUE TITLE
Need Temperature/Max_token Options

### ISSUE THREAD

**Issue by cytusbox** [ollama/ollama-python#214]
My python script:
```python
from ollama import Client
client = Client(host=args.base_url)
chat_completion = client.chat(
    messages=[
        {
            "role": "user",
            "content": full_prompt,
        },
    ],
    model=args.model,
    temperature = args.temp # TO SET THE TEMPERATURE OF MODEL
)
```
Is there any way to set temperature/max_token options through python api?

**Comment by Orest02** [comment]
there's an API documentation that gives a deeper insight on additional parameters you can use, you might be looking for this section:
https://github.com/ollama/ollama/blob/main/docs/api.md#generate-request-with-options

**Comment by cytusbox** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lennartpollvogt** [comment]
The chat function has the argument `options` (a dictionary) to provide such configurations. Here is an example for setting the temperature.

```Python
from ollama import Client
client = Client(host=args.base_url)
chat_completion = client.chat(
    messages=[
        {
            "role": "user",
            "content": full_prompt,
        },
    ],
    model=args.model,
    options={temperature:0.5}
)
```

You will find in the docs of the Ollama repository the full documentation of these options (see comment above)
