### ISSUE TITLE
GUI using Gradio or Pygame or Streamlit

### ISSUE THREAD

**Issue by MostlyKIGuess** [ollama/ollama-python#22]
- We would have a better interface and keep modes for changing the model.
- For the model change we will the GUI so that it will be vv easy for the user to change the model.
- I would love to work on this if someone is ready to guide along with it.. I am familiar with Gradio,Pygame and Streamlit.
- One inspiration is this privateGPT UI using Gradio:
![image](https://github.com/ollama/ollama-python/assets/135974627/324ba56b-115b-471f-bbdc-979a3724ff5f)

**Comment by vinay235** [comment]
There are many GUIs available for ollama if your ask is that. Check out the list in their repo. My fav is ollama-webui

**Comment by mxyng** [comment]
There are many community built web and desktop UI. Here's a non-exhaustive [list](https://github.com/ollama/ollama#web--desktop). The intent with this project is to create a foundation for the community to build tools and applications so a UI is out of scope.

Feel free to use this project or [ollama-js](https://github.com/ollama/ollama-js) to build your own GUI if the ones I mentioned above don't satisfy your use case!
