### ISSUE TITLE
Is there a command that just serves the  REST api , similar to ollama run on the cli

### ISSUE THREAD

**Issue by gregnwosu** [ollama/ollama-python#23]
I want to serve the API  from python in a similar way  as 
```bash
ollama run mistral
```
maybe that returns a server reference that can be used to shutdown the model once done. 
Happy to contribute if there is a need

**Comment by furqanalishah** [comment]
@gregnwosu thanks. 
Could please tell us about a use case when you would need it?

**Comment by mxyng** [comment]
This project is intended to be a thin client library for the Ollama API. A running ollama instance is required. You can change which instance the library uses by manually creating a client `ollama.Client(host='')` or by setting `OLLAMA_HOST`
