### ISSUE TITLE
Bug in tool_calls response parsing

### ISSUE THREAD

**Issue by evilsocket** [ollama/ollama-python#233]
[This should be "arguments", not "args"](https://github.com/ollama/ollama-python/blob/main/ollama/_types.py#L64)

**Comment by zeelrupapara** [comment]
I got it...
I also found here in the response: https://github.com/ollama/ollama/blob/main/docs/api.md#chat-request-with-tools
So in response, we got the arguments not args in json

**Comment by evilsocket** [comment]
yep! simple fix that will *actually* enable function calling :D

**Comment by joshyan1** [comment]
Thanks for all the help. Closed by https://github.com/ollama/ollama-python/pull/236
