### ISSUE TITLE
Clarification: Does this install ollama or just act as an API to an existing install?

### ISSUE THREAD

**Issue by ganakee** [ollama/ollama-python#24]
Looks like an interesting project and thanks for the work on it.

I reviewed the source. It seems that this acts as an API and DOES NOT install ollama itself. I want to verify that this does NOT install Ollama.

I ask because I have a custom-compiled version of ollama for AMD GPUs (difficult to do). My custom-compiled ollama instance launches via systemd. 

 I would not want this API to overwrite any of my ollama files. 

Is there any confirmation/clarification on this API?

**Comment by mrkiura** [comment]
This acts as an API to an existing (running) install.

**Comment by mxyng** [comment]
The above comment is correct. This is _only_ a Python wrapper for the API. It does not install nor run ollama itself
