### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by varunshenoy** [ollama/ollama-python#25]
Is there any way to batch prompts with local models using this package? Thank you!

**Comment by mxyng** [comment]
Can you describe what you're trying to do? I'm not sure I understand

**Comment by varunshenoy** [comment]
Suppose I have a list of prompts: ["A list of colors: red, blue", "Geckos eat", "The capital of France is"]

You can run these all through an LLM in a single forward pass with a little to no latency hit due to the inherent parallelism in transformers. Mainly used for inference servers with multiple people hitting it at the same time, but I want to see if I can speed up some local workflows.

Here's some documentation from Hugging Face's `transformers` library that explains how they support batching:
<img width="905" alt="SCR-20240125-lbxs" src="https://github.com/ollama/ollama-python/assets/10859091/c82b6f01-73bb-4acd-ae66-1a3d70945dce">

**Comment by mxyng** [comment]
This issue would be more appropriate for [ollama](https://github.com/ollama/ollama) since this repo is only the python interface to the ollama API.
