### ISSUE TITLE
Inconsistent API Behavior

### ISSUE THREAD

**Issue by negaralizadeh** [ollama/ollama-python#251]
I checked the documentation several times and I'm using the generate function in this way:

options = {
    "temperature": 0.2,
    "top_p": 0.8,
    "seed": 42,
    "num_predict": 300,
}
ollama.generate(model=model_name, prompt=prompt, stream=False, options=options, system=system_message, format="json")

Although I set the **stream flag to false**, I still don't get the whole response in one package (done = False in the first received package).
The other problem is that sometimes, even when the package is final (done=true), I don't see all the expected additional information there for example _prompt_eval_count_ is missing.

Am I doing something wrong here?

**Comment by ParthSareen** [comment]
Hey! Are you still running into this? If so could you send an example of a run and the output it gives you.

**Comment by ParthSareen** [comment]
Closing out as stale
