### ISSUE TITLE
Return python object instead of JSON

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [ollama/ollama-python#257]
Is it on the roadmap to return a Python object instead of a dictionary?

If it is, the solution is to create Pydantic classes for everything and the parse the JSON object with the [`model_validate_json`](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_validate_json) function

**Comment by RithikRaj64** [comment]
Yeah that would be a better way to manage stuff.

**Comment by ParthSareen** [comment]
Added with the new release! @Siddhesh-Agarwal @RithikRaj64 :)
