### ISSUE TITLE
ConnectError

### ISSUE THREAD

**Issue by morteza-rp** [ollama/ollama-python#27]
what should i do?
ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by mxyng** [comment]
It seems ollama is either not running or the client isn't configured to use a non-default host value. The default is `http://127.0.0.1:11434`

This library needs a running ollama instance. If one is running on a non-default host or port, you can configure the library by either creating a custom client `ollama.Client(host='')` or by setting OLLAMA_HOST

**Comment by neonarc4** [comment]
@mxyng its not working either 
![image](https://github.com/ollama/ollama-python/assets/140290288/9b65876f-531f-45f5-aa57-f22b1c1a8794)
