### ISSUE TITLE
Please expose the contents of the `_type` file to allow for better static type analysis

### ISSUE THREAD

**Issue by johnch18** [ollama/ollama-python#274]
I am writing some wrapper/library code using Ollama, and I'm running into issues when trying to type hint. Not all of the types used in the library are public, and I would appreciate if that were to be remedied.

The simplest fix at present would be to include the contents of `_type` in the ollama `__init__` file.

Thanks

**Comment by mxyng** [comment]
More types will be exported in the next release. I have a change _almost_ ready for a PR
