### ISSUE TITLE
README doesn't mention that a running ollama server is required

### ISSUE THREAD

**Issue by jmccrosky** [ollama/ollama-python#29]
It seems I'm not the only one that looked at the README and assumed that the library is taking care of running the backend, resulting in a "Connection Refused" error when I try the example code in the README.  If I understand well, I need to first run the ollama server.  This should perhaps be made clear in the README.

**Comment by g1ra** [comment]
this must be very frustrating for most of the users starting

**Comment by diegodmb** [comment]
How can I run de Ollama Server? I'm encounter this error in my django App:
[WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión

**Comment by connor-makowski** [comment]
You need to have a local ollama server running to be able to continue. To do this:

- Download: https://ollama.com/
- Run an LLM: https://ollama.com/library
    - Example: `ollama run llama2`
    - Example: `ollama run llama2:70b`

There is a PR to add this to the docs (mentioned above).

**Comment by connor-makowski** [comment]
I had to update the Readme when working on iterative chats (chats with history), so I ended up migrating in these changes into the PR here: https://github.com/ollama/ollama-python/pull/64

**Comment by ParthSareen** [comment]
Revisiting issues - think that following covers the part about running the model.
> The Ollama Python library provides the easiest way to integrate Python 3.8+ projects with [Ollama](https://github.com/ollama/ollama).
