### ISSUE TITLE
Error: Head "http://127.0.0.1:11434/": read tcp 127.0.0.1:36136->127.0.0.1:11434: read: connection reset by peer

### ISSUE THREAD

**Issue by wildcat7534** [ollama/ollama-python#30]
I just install the last ollama better for WSL but.... : 
:~$ ollama serve
2024/01/26 17:13:58 images.go:857: INFO total blobs: 7
2024/01/26 17:13:58 images.go:864: INFO total unused blobs removed: 0
2024/01/26 17:13:58 routes.go:950: INFO Listening on 127.0.0.1:11434 (version 0.1.21)
2024/01/26 17:13:58 payload_common.go:106: INFO Extracting dynamic libraries...
2024/01/26 17:14:00 payload_common.go:145: INFO Dynamic LLM libraries [cpu rocm_v6 cuda_v11 cpu_avx rocm_v5 cpu_avx2]
2024/01/26 17:14:00 gpu.go:93: INFO Detecting GPU type
2024/01/26 17:14:00 gpu.go:212: INFO Searching for GPU management library libnvidia-ml.so
2024/01/26 17:14:01 gpu.go:258: INFO Discovered GPU libraries: [/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.545.23.08 /usr/lib/wsl/lib/libnvidia-ml.so.1 /usr/lib/wsl/drivers/nv_dispi.inf_amd64_2fe7c165c5dd3267/libnvidia-ml.so.1 /usr/lib/wsl/drivers/nv_dispi.inf_amd64_72a60bcfb646da4c/libnvidia-ml.so.1]
SIGSEGV: segmentation violation
PC=0x7f0522649a70 m=11 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x9b6eb0, 0xc0007438a8)
        /usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc000743880 sp=0xc000743848 pc=0x409b0b
github.com/jmorganca/ollama/gpu._Cfunc_cuda_init(0x7f0538000b70, 0xc000036a80)
        _cgo_gotypes.go:248 +0x3f fp=0xc0007438a8 sp=0xc000743880 pc=0x7b9cdf
github.com/jmorganca/ollama/gpu.LoadCUDAMgmt.func2(0xc00043cf10?, 0x33?)
        /go/src/github.com/jmorganca/ollama/gpu/gpu.go:268 +0x4a fp=0xc0007438e8 sp=0xc0007438a8 pc=0x7bbaca
github.com/jmorganca/ollama/gpu.LoadCUDAMgmt({0xc0000919c0, 0x4, 0xc0000ca370?})
        /go/src/github.com/jmorganca/ollama/gpu/gpu.go:268 +0x1b8 fp=0xc000743988 sp=0xc0007438e8 pc=0x7bb998
github.com/jmorganca/ollama/gpu.initGPUHandles()
        /go/src/github.com/jmorganca/ollama/gpu/gpu.go:96 +0xd1 fp=0xc0007439f0 sp=0xc000743988 pc=0x7ba131
github.com/jmorganca/ollama/gpu.GetGPUInfo()
        /go/src/github.com/jmorganca/ollama/gpu/gpu.go:121 +0xb5 fp=0xc000743b00 sp=0xc0007439f0 pc=0x7ba2f5
github.com/jmorganca/ollama/gpu.CheckVRAM()
        /go/src/github.com/jmorganca/ollama/gpu/gpu.go:194 +0x1f fp=0xc000743ba8 sp=0xc000743b00 pc=0x7bafdf
github.com/jmorganca/ollama/server.Serve({0x106c11d0, 0xc000451580})
        /go/src/github.com/jmorganca/ollama/server/routes.go:972 +0x453 fp=0xc000743c98 sp=0xc000743ba8 pc=0x99b513
github.com/jmorganca/ollama/cmd.RunServer(0xc000472300?, {0x10b06800?, 0x4?, 0xad25c1?})
        /go/src/github.com/jmorganca/ollama/cmd/cmd.go:692 +0x199 fp=0xc000743d30 sp=0xc000743c98 pc=0x9ad9f9
github.com/spf13/cobra.(*Command).execute(0xc0003f3800, {0x10b06800, 0x0, 0x0})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c fp=0xc000743e68 sp=0xc000743d30 pc=0x7641dc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003f2c00)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5 fp=0xc000743f20 sp=0xc000743e68 pc=0x764a05
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
        /go/src/github.com/jmorganca/ollama/main.go:11 +0x4d fp=0xc000743f40 sp=0xc000743f20 pc=0x9b5a2d
runtime.main()
        /usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc000743fe0 sp=0xc000743f40 pc=0x43e25b
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000743fe8 sp=0xc000743fe0 pc=0x46e0a1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000066fa8 sp=0xc000066f88 pc=0x43e6ae
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:404
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:322 +0xb3 fp=0xc000066fe0 sp=0xc000066fa8 pc=0x43e533
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000066fe8 sp=0xc000066fe0 pc=0x46e0a1
created by runtime.init.6 in goroutine 1
        /usr/local/go/src/runtime/proc.go:310 +0x1a
        
        etc etc
        
        i f I try : 
        :~$ curl http://localhost:11434/api/chat -d '{
  "model": "llama2",
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]
}'

>>> curl: (56) Recv failure: Connection reset by peer

Everything was find before (core i9 11900k, 120Go, NVME, rtx3090)

**Comment by dhiltgen** [comment]
Dup of #2198 and fixed in v0.1.22
