### ISSUE TITLE
Exception: Attempted to call a sync iterator on an async stream.

### ISSUE THREAD

**Issue by nlp4everyone** [ollama/ollama-python#309]
When i try to stream tokens from Async Client, sometimes this exception happens: 
![exception](https://github.com/user-attachments/assets/f0c8a322-7c21-4a38-bed3-33c6f65a9813)
This is my code, from example of Official Ollama Github:
![code](https://github.com/user-attachments/assets/cab6ec12-6e73-4f1f-9939-d0e6d5979803)
Anybody encountered this issue before?

**Comment by xcq2000** [comment]
try close the VPN

**Comment by ParthSareen** [comment]
Closing this out - let me know if you're still running into this :) @nlp4everyone
