### ISSUE TITLE
Check tool called when stream is set to true

### ISSUE THREAD

**Issue by javixeneize** [ollama/ollama-python#310]
Hi

I am validating in my code which tools are called in Ollama by printing this:

print(response["message"].get("tool_calls"))

When i set stream to true like this

```
    response = client.chat(
        model="llama3.2",
        messages=messages,
        tools=tools,
        stream=True)
    for chunk in response:
        yield chunk["message"]["content"]
   print(response["message"].get("tool_calls"))
```

I have this error

TypeError: 'generator' object is not subscriptable

How can i check which tools the LLM is calling when stream is set to true?

Thanks

**Comment by ParthSareen** [comment]
Hey! Since yield is a generator you'd have to convert it something you can access. You'd need to yield to a variable and then convert to a list. I'd just recommend checking out our example: https://github.com/ollama/ollama-python/blob/main/examples/tools/main.py

**Comment by javixeneize** [comment]
Hi

Yeah, i checked that example but it doesnt stream the output. I know how to use tools, what i need to know is how to use tools together with the stream functionality

@ParthSareen  can you help me with an example that combines stream and tools in the same call?


Thanks

**Comment by ParthSareen** [comment]
We don't have streaming tools enabled yet unfortunately but it is something we are looking into!

**Comment by javixeneize** [comment]
Thanks! i will keep an eye into it

**Comment by AlejoPrietoDavalos** [comment]
Hi @ParthSareen.
I need the same thing, to be able to use stream=True and have a reliable way to know if there was a tool call or if I should just stream the bot's response.
Is there an issue where this is being discussed?
Thanks

**Comment by ParthSareen** [comment]
@AlejoPrietoDavalos you'd currently be able to either see complete tool calls or a chunk of the response with `content` so you have a way to decipher whether tools are coming or not
