### ISSUE TITLE
Model doesn't ger offloaded from VRAM after deletion

### ISSUE THREAD

**Issue by tianci216** [ollama/ollama-python#338]
I have a custom script that creates (with ollama.create()) a model when using, and deletes the model after the job is done (with ollama.delete()). However, I realize the model is kept in VRAM after deletion, but the model has already been removed from the model list, therefore stopping the model from running with ollama CLI is impossible, the only way to offload the model is to restart ollama.

Is there a function in Ollama python library that could offload the model? Thanks!

**Comment by ParthSareen** [comment]
Hey - can you make sure you're on the latest version of Ollama? And then if you're still running into this issue - this seems like a bug in https://github.com/ollama/ollama - so would appreciate it if you can open the issue there!
