### ISSUE TITLE
craete function ollama._types.ResponseError

### ISSUE THREAD

**Issue by qq1273834091** [ollama/ollama-python#342]
I prompted an error when using the create function

def createModelFile():
    path="/root/data/finetuneFile/modelExport/modelgguf/mytest1.gguf"
    modelfile = f"""
    FROM {path}
    """
    for response in create(model="exe", modelfile=modelfile, stream=True):
        print(response['status'])

<img width="854" alt="image" src="https://github.com/user-attachments/assets/44ef4e2d-3e75-4eed-b3d9-0e5051e472a7">

**Comment by ParthSareen** [comment]
Hey! Seems like it's not able to find your gguf file - could you check the path again? Thanks
