### ISSUE TITLE
about maintaining session continuity: how to get context by python clinet

### ISSUE THREAD

**Issue by huijunzi** [ollama/ollama-python#343]
If using an HTTP client, the context can be obtained from the last returned JSON of the previous generate request, and this context can be passed as a context parameter in the new generate, thus maintaining session continuity. However, when using a Python client, it is not possible to obtain the context in the JSON returned by the last request, making it impossible to implement this function. Does the Python client not provide this feature?

**Comment by ParthSareen** [comment]
Hey! The pattern is a bit different when using the chat interface. Refer to this example here to see how you can attach assistant responses: https://github.com/ollama/ollama-python/blob/main/examples/chat-with-history.py
