### ISSUE TITLE
Calling chat with function as tool gives an empty response

### ISSUE THREAD

**Issue by mjm9189** [ollama/ollama-python#345]
I defined a test function as:
```
def alfalfa(a, b):
    if a % 2 == 0 and b % 2 == 0:
        return a + b
    elif (a % 2 != 0) and (b % 2 != 0):
        return a * b
    else:
        return 72340
```
I initialize it as a tool using:
```
alftool = {
      'type': 'function',
      'function': {
        'name': 'alfalfa',
        'description': 'Returns the alfalfa of two numbers',
        'parameters': {
          'type': 'object',
          'properties': {
            'a': {
              'type': 'integer',
              'description': 'First number to alfalfa',
            },
            'b': {
                'type': 'integer',
                'description': 'Second number to alfalfa',
            }
          },
          'required': ['a', 'b'],
        },
      },
    }
```
Finally, using `oclient = ollama.Client(host="localhost")`, I call:
```
response = oclient.chat(
    model='llama3.2:3b-instruct-q8_0',
    messages=[{'role': 'user', 'content':
        'Please alfalfa 2 and 4'}],
    tools=[alfalfa]
)

print(response['message'])
print(response.message.content)
```

The latter prints nothing, while the former prints `role='assistant' content='' images=None tool_calls=[ToolCall(function=Function(name='alfalfa', arguments={'a': '2', 'b': '4'}))]`. When I omit the `tools=...`, I get a response as normal:
```
Alfalfa doesn't actually mean "to add" or perform mathematical operations. Alfalfa is a type of leguminous herb that is commonly used as hay for livestock.

If you meant to ask me to calculate the result of 2 + 4, I'd be happy to help!

Here's the answer:

2 + 4 = 6
```
I had similar results with other functions tested. This is on the latest version (v0.4.1).

**Comment by ameen-91** [comment]
Its the expected behaviour. In `[ToolCall(function=Function(name='alfalfa', arguments={'a': '2', 'b': '4'}))]`, the tool is being called with the correct parameters.

As for the json definition, I can get the output:

```python
alftool = {
      'type': 'function',
      'function': {
        'name': 'alfalfa',
        'description': 'Returns the alfalfa of two numbers',
        'parameters': {
          'type': 'object',
          'properties': {
            'a': {
              'type': 'integer',
              'description': 'First number to alfalfa',
            },
            'b': {
                'type': 'integer',
                'description': 'Second number to alfalfa',
            }
          },
          'required': ['a', 'b'],
        },
      },
    }

response = ollama.chat(
    model='llama3.1:8b-instruct-q4_0',
    messages=[{'role': 'user', 'content':
        'Please alfalfa 2 and 4'}],
    tools=[alftool]
)

print(response['message'])
```
Output:

```python
role='assistant' content='' images=None tool_calls=[ToolCall(function=Function(name='alfalfa', arguments={'a': 2, 'b': 4}))]
```

**Comment by mjm9189** [comment]
Just to clarify, the expected behavior of asking the model a question is to receive no answer? I can see this behaviour being useful for cases such as asking the model to turn on/off a setting in an app, but does the current state of the api allow for the model to use tools to inform its response to the user?

**Comment by ParthSareen** [comment]
@mjm9189 Hey! So the initial call to the LLM just generates a toolcall - which is what you need to use to execute your function with the provided params. You can pass the output of the tool back to the LLM and generate a response for the user. There's an example in the JS repo for this - will add one for python soon too! https://github.com/ollama/ollama-js/blob/main/examples/tools/tools.ts 

Hope this helps!

**Comment by mjm9189** [comment]
Amazing, thank you for the help! I'd only looked through the Python one so far, but I'm glad it's being updated soon. Thanks again!

**Comment by ParthSareen** [comment]
@mjm9189 Just updated! https://github.com/ollama/ollama-python/blob/main/examples/tools.py

**Comment by rsanchezmo** [comment]
I was unable to get both a function call and an output on the same model inference (I used llama 3.1:8b). I mean, for a ReAct agent for example, you can ask first to do the THOUGHT process and choose the tools that help you achieve the plan (or the initial steps of it). Then You will feedback the model with the tool output as you did and let the model decide between giving a final answer or replaning (or moving to next step) and call to another set of tools until the agent completed the task.

Is incompatible function calling + generation on the same step? meaning thinking a bit then deciding what tools to use? It has demonstrated to be more performant...

Thanks in advance!
