### ISSUE TITLE
Error while working with multimodal chat LLaMa 3.2-vision 90B

### ISSUE THREAD

**Issue by PZherdev** [ollama/ollama-python#347]
Hello everyone

I'm trying to check working with images by llama 3.2 vision. With code from example:

```
image_path = 'myimage.jpg' 

#img = base64.b64encode(pathlib.Path(image_path).read_bytes()).decode()
# or the raw bytes
#img = pathlib.Path(image_path).read_bytes()

messages = [
  {
    'role': 'user',
     'content': f'Desribe image',
     'images' : [image_path]
  },
]

for part in ollama.chat('llama3.2-vision:90b', messages=messages, stream=True):
  print(part['message']['content'], end='', flush=True)

print()
```
But getting an error:

`ResponseError: POST predict: Post "http://127.0.0.1:44183/completion": EOF`

Version ollama: 0.4.6

**Comment by ParthSareen** [comment]
Hey! Can you double check that Ollama is running and you're hitting the right endpoint? The default is usually `'http://127.0.0.1:11434'`. Maybe instantiate a client with the url set and see if that works? Can dig a bit more if you're still running into it.

**Comment by jessegross** [comment]
@PZherdev That message likely indicates a crash in the underlying inference runner. Can you file a new bug in [ollama/ollama](https://github.com/ollama/ollama) and include [server logs](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md#how-to-troubleshoot-issues)?
