### ISSUE TITLE
Model doesn't seem to include tool output in its response

### ISSUE THREAD

**Issue by mjm9189** [ollama/ollama-python#357]
This issue is built off of the code I detailed in #345. After running effectively the same code I included there (with the one alteration being requesting the model to perform "alfalfa" on 2 and 3, rather than 2 and 4), I follow python example on generating a response based on the outcome of the tool call as follows:
```
if response.message.tool_calls:
    for tool in response.message.tool_calls:
        if function_to_call := toolfuncs[tool.function.name]:
            print('Calling function:', tool.function.name)
            print('Arguments:', tool.function.arguments)
            output = function_to_call(**tool.function.arguments)
            print('Function output:', output)
            messages.append(response.message)
            messages.append({'role': 'tool', 'content': str(output), 'name': tool.function.name})
final_response = oclient.chat(model="llama3.2:3b-instruct-q8_0", messages=messages)
```
This prints the following:
```
Calling function: alfalfa
Arguments: {'a': '2', 'b': '3'}
Function output: 72340
```
This indicates that the tool was chosen and called successfully. For multiple attempts at making the same request this remained consistently true. However, when I then print `final_response.message.content` I find that the model either doesn't understand what "alfalfa" means (despite understanding it well enough to call the tool), or simply makes up its own meaning for it.

**Comment by ParthSareen** [comment]
So it truly depends on what your initial prompt is for the model, what your prompt is to get the final response, and the size of the model you're using.
1. Initial prompt - to get the best performance you should probably tell the model what all tools it's has access to even in the system prompt (although it does get passed in later as well)
2. Would recommend the final prompt to be something along the lines of "the tool output is attached and the function run was {function_to_call}, tell the user the final output of the function" 
3. Larger models will inherently perform better - would recommend at least an 8b model for this
