### ISSUE TITLE
There is a problem using ollama in vscode+jupyter

### ISSUE THREAD

**Issue by szzhh** [ollama/ollama-python#374]
I am using Windows system locally. I use vscode+jupyter to remotely connect to Linux server and start ollama service. When I run ollama.list(), the model output is the model downloaded locally. However, when I run the magic command! ollama list command, it outputs the model of the remote server. And the jupyter I created remotely can only use the local ollama model, not the remote model.
![PixPin_2024-12-12_19-29-47](https://github.com/user-attachments/assets/da3933e2-526a-4f51-bcdb-e884fcefe39b)

**Comment by ParthSareen** [comment]
Hi @szzhh - to do this you can either to pass in your own http client or `export OLLAMA_HOST=HOSTNAME` to point Ollama to the right spot
