### ISSUE TITLE
How can I use `context` parameter?

### ISSUE THREAD

**Issue by YRG999** [ollama/ollama-python#38]
How can I use the `context` parameter [from the API](https://github.com/ollama/ollama/blob/main/docs/api.md#parameters) to keep a conversational memory?

**Comment by mxyng** [comment]
The response from a generate call will return a context object. To continue the conversation, you can pass this directly into the next call:

```python
r1 = ollama.generate(model='llama2', prompt='hi!')
r2 = ollama.generate(model='llama2', prompt='hi again!', context=r1['context'])
```

Context is the token representations of the inputs and outputs up to and including the response
