### ISSUE TITLE
Usage body for LLaVA model

### ISSUE THREAD

**Issue by sanujenLLM** [ollama/ollama-python#44]
What is the request body for the LLaVA model which needs to handle image inputs along with text?

This is the sample provided in the repo for the llama2 model.
```
import ollama
response = ollama.chat(model='llama2', messages=[
  {
    'role': 'user',
    'content': 'Why is the sky blue?',
  },
])
print(response['message']['content'])
```

**Comment by mxyng** [comment]
llava is a multimodal model. There's an example [here](https://github.com/ollama/ollama-python/blob/v0.1.5/examples/multimodal/main.py#L26)
