### ISSUE TITLE
:memo: Documentation request - for fewshot templates model

### ISSUE THREAD

**Issue by adriens** [ollama/ollama-python#46]
# :grey_question: About

In the latest `ollama` ([`v0.1.22`](https://github.com/ollama/ollama/releases/tag/v0.1.22)) supports kind of fewshot templates, see [history](https://github.com/ollama/ollama/commit/b706794905cc154a269f099c804ddfd8bed1f1b2#diff-cdd8989188011fbb3b5c14846bb2cb6d7156d2bc81ad46ccda1151f72a0489e8R209) : 

![image](https://github.com/ollama/ollama-python/assets/5235127/758b66e0-e652-4575-b6c3-f032968fc9c4)

```
MESSAGE user Is Toronto in Canada?
MESSAGE assistant yes
MESSAGE user Is Sacramento in Canada?
MESSAGE assistant no
MESSAGE user Is Ontario in Canada?
MESSAGE assistant yes
```

# :dart: Action

It would be interesting to put this in the ["Create"  section](https://github.com/ollama/ollama-python?tab=readme-ov-file#create) as this feature has a great potential.

**Comment by mxyng** [comment]
This is a feature of the Modelfile and does not require any special handling client-side, as long as your Ollama server is >=0.1.22
