### ISSUE TITLE
:pray: Feature request > Create model from file path with SDK

### ISSUE THREAD

**Issue by adriens** [ollama/ollama-python#53]
# :grey_question: About

Currently we can [create model from sdk](https://github.com/ollama/ollama-python?tab=readme-ov-file#create) this way;

```python
modelfile='''
FROM llama2
SYSTEM You are mario from super mario bros.

ollama.create(model='example', modelfile=modelfile)'''
```

:thinking: Sometimes, it could be even easier to load a file **directly by provding the model file (possibly generated by third party process) path to the SDK** so the code would become:

```python
modelfile='./customModelFile'

ollama.create(model='example',
    modelfilepath = modelfile)
```

**Comment by mxyng** [comment]
This is possible in a couple ways. Here are some examples:

Using the `path` keyword argument:

```python
ollama.create(model='name', path=modelfilepath)
```

Reading the file explicitly:

```python
with open(modelfilepath) as f:
  ollama.create(model='name', modelfile=f.read())
```
