### ISSUE TITLE
Where does ollama.pull() store the models?

### ISSUE THREAD

**Issue by HotLoverGirl69** [ollama/ollama-python#60]
Where does ollama-python store the pulled models to?

**Comment by mxyng** [comment]
ollama-python doesn't store models. it's a client library to ollama. models are stored on the server. see the [faq](https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored) for details

**Comment by shohagkhan2509-cmyk** [comment]
infinix
