### ISSUE TITLE
From ollama to transformer.AutoModelForCausalLM

### ISSUE THREAD

**Issue by Demirrr** [ollama/ollama-python#71]
Dear all,

Thank you for ollama-python.

I was wondering whether it would be possible to `create transformers.AutoModelForCausalLM` from ollama, e.g.,
```python
import ollama
model, tokenizer = ollama.from('mixtral:8x7b ')
```
where
+ model is an instance of `transformers.AutoModelForCausalLM`
+ tokenizer is an instance of `transformers.AutoTokenizer`

**Comment by mxyng** [comment]
It's not (currently) possible to convert an ollama model back into a transformers model
