### ISSUE TITLE
How to set temprature and output token size in the chat mode?

### ISSUE THREAD

**Issue by jojogh** [ollama/ollama-python#76]
Is there any examples to guide how to set temprature and output token size in the chat mode?

**Comment by eliranwong** [comment]
You may read this example:

examples/fill-in-middle/main.py

**Comment by deepcoder** [comment]
and "keep_alive" as well, thanks!

**Comment by jojogh** [comment]
> For example, I use the following for one of my projects:
> 
> ```
> from ollama import Options
> ```
> 
> ```
>         completion = ollama.chat(
>             #keep_alive=0,
>             model=config.ollamaDefaultModel,
>             messages=[
>                 *ongoingMessages,
>                 {
>                     "role": "user",
>                     "content": prompt,
>                 },
>             ],
>             format="json",
>             stream=True,
>             options=Options(
>                 temperature=0.0,
>                 num_ctx=8192,
>                 num_predict=-1,
>             ),
>         )
> ```

Thanks Wong, I will try. Many thanks.
