### ISSUE TITLE
How do I define the 'base_url' using embeddings()

### ISSUE THREAD

**Issue by pandego** [ollama/ollama-python#77]
Hello, this might be extremely basic, but when I try to run the following command:
```
result = ollama.embeddings(
        model="nomic-embed-text", 
        prompt=prompt, 
        base_url="http://10.1.8.100:11434",
        )
```
I get the following unexpected argument `base_url`:
```
result = ollama.embeddings(
         ^^^^^^^^^^^^^^^^^^
TypeError: Client.embeddings() got an unexpected keyword argument 'base_url'
```
What am I missing? 🥲 Thanks!

**Comment by mxyng** [comment]
The module level client is intended for quick integration using default client configurations. If you want to change things like `base_url,` you need to instantiate a new client

```python
client = ollama.Client(base_url="http://10.1.8.100:11434")
client.embeddings(...)
```

Alternatively, you can use the module-level client and set base URL with `OLLAMA_HOST`

```
$ export OLLAMA_HOST=10.1.8.0
$ python -c 'import ollama; ollama.embeddings(...)'
```

**Comment by alexiewx** [comment]
@mxyng  tks !  it works for me .
