### ISSUE TITLE
terribly slow: format="json", stream=False, please advise

### ISSUE THREAD

**Issue by eliranwong** [ollama/ollama-python#79]
I appreciate great work achieved with ollama.  I see a lot of potential of use.

However, when I tested.  I found that the generate and chat function takes way too long time to response, when I set format="json" and stream=False.  Speed normal with non-json mode and stream.  Please advise.  many thanks.

**Comment by tof43** [comment]
Hey, I have the same behaviour, any clue on how you solved it ?
