### ISSUE TITLE
Can I set num_ctx=-1 to use max possible context window?

### ISSUE THREAD

**Issue by eliranwong** [ollama/ollama-python#84]
Can I set num_ctx=-1 to use max possible context window?

so I don't need to change its value for different models

**Comment by jmorganca** [comment]
Hi there, you can set it to a large value (e.g. 16k, 1M) and Ollama will automatically use the largest context window the model was trained against. Hope this helps

**Comment by eliranwong** [comment]
Your suggestion does not work in some models I tested.  It just hangs forever without response, if I set num_ctx too high.

**Comment by yusufcanb** [comment]
I can agree that, most of the Qwen models hang if `num_ctx` too high.
