### ISSUE TITLE
Setting up top k , Max tokens , context length ?

### ISSUE THREAD

**Issue by timtensor** [ollama/ollama-python#87]
Hi I am using an ollama chat model to call Mistral-model . How can one set the different parameters such as top k , top p, context, length and temperature ? 

T

**Comment by mxyng** [comment]
You can set it with the `options` keyword parameter, e.g. `ollama.chat(..., options={...})`. There's an example [here](https://github.com/ollama/ollama-python/blob/main/examples/fill-in-middle/main.py#L14-L19)
